[2021-12-09 15:52:32,913] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: brent_pricing_dag.choose_best_model manual__2021-12-09T20:47:50.813544+00:00 [queued]>
[2021-12-09 15:52:32,920] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: brent_pricing_dag.choose_best_model manual__2021-12-09T20:47:50.813544+00:00 [queued]>
[2021-12-09 15:52:32,920] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 15:52:32,920] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-09 15:52:32,920] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 15:52:32,927] {taskinstance.py:1262} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2021-12-09 20:47:50.813544+00:00
[2021-12-09 15:52:32,930] {standard_task_runner.py:52} INFO - Started process 31376 to run task
[2021-12-09 15:52:32,935] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'brent_pricing_dag', 'choose_best_model', 'manual__2021-12-09T20:47:50.813544+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_brent_pricing.py', '--cfg-path', '/var/folders/b3/j_ybgjv53p33dy62wlktdr4m0000gp/T/tmp3ld83awn', '--error-file', '/var/folders/b3/j_ybgjv53p33dy62wlktdr4m0000gp/T/tmpd7rsx35i']
[2021-12-09 15:52:32,938] {standard_task_runner.py:77} INFO - Job 73: Subtask choose_best_model
[2021-12-09 15:52:37,963] {logging_mixin.py:109} INFO - Running <TaskInstance: brent_pricing_dag.choose_best_model manual__2021-12-09T20:47:50.813544+00:00 [running]> on host zipcodes-MacBook-Pro-3.local
[2021-12-09 15:52:43,006] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=brent_pricing_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2021-12-09T20:47:50.813544+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-09T20:47:50.813544+00:00
[2021-12-09 15:52:43,012] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 180, in execute
    branch = super().execute(context)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/ballakeerthi/dev/airflow/dags/dag_brent_pricing.py", line 45, in _choose_best_model
    if i[1]>highest_val:
IndexError: list index out of range
[2021-12-09 15:52:43,028] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=brent_pricing_dag, task_id=choose_best_model, execution_date=20211209T204750, start_date=20211209T205232, end_date=20211209T205243
[2021-12-09 15:52:43,035] {standard_task_runner.py:88} ERROR - Failed to execute job 73 for task choose_best_model
Traceback (most recent call last):
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 180, in execute
    branch = super().execute(context)
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/ballakeerthi/dev/Airflow/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/ballakeerthi/dev/airflow/dags/dag_brent_pricing.py", line 45, in _choose_best_model
    if i[1]>highest_val:
IndexError: list index out of range
[2021-12-09 15:52:43,074] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-09 15:52:43,090] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
