[2021-12-06 11:25:39,774] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: brent_pricing_dag.Create_dummy_variables scheduled__2021-12-05T00:00:00+00:00 [queued]>
[2021-12-06 11:25:39,780] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: brent_pricing_dag.Create_dummy_variables scheduled__2021-12-05T00:00:00+00:00 [queued]>
[2021-12-06 11:25:39,781] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-06 11:25:39,781] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-06 11:25:39,781] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-06 11:25:39,790] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): Create_dummy_variables> on 2021-12-05 00:00:00+00:00
[2021-12-06 11:25:39,796] {standard_task_runner.py:52} INFO - Started process 12594 to run task
[2021-12-06 11:25:39,802] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'brent_pricing_dag', 'Create_dummy_variables', 'scheduled__2021-12-05T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_brent_pricing.py', '--cfg-path', '/var/folders/b3/j_ybgjv53p33dy62wlktdr4m0000gp/T/tmp4qyrd8s4', '--error-file', '/var/folders/b3/j_ybgjv53p33dy62wlktdr4m0000gp/T/tmpyka0r7yb']
[2021-12-06 11:25:39,806] {standard_task_runner.py:77} INFO - Job 18: Subtask Create_dummy_variables
[2021-12-06 11:25:44,850] {logging_mixin.py:109} INFO - Running <TaskInstance: brent_pricing_dag.Create_dummy_variables scheduled__2021-12-05T00:00:00+00:00 [running]> on host zipcodes-MacBook-Pro-3.local
[2021-12-06 11:25:49,891] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=keerthiballa@gmail.com
AIRFLOW_CTX_DAG_OWNER=kballa
AIRFLOW_CTX_DAG_ID=brent_pricing_dag
AIRFLOW_CTX_TASK_ID=Create_dummy_variables
AIRFLOW_CTX_EXECUTION_DATE=2021-12-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-05T00:00:00+00:00
[2021-12-06 11:25:49,893] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: create_dummy_vars() missing 1 required positional argument: 'dataset'
[2021-12-06 11:25:49,903] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=brent_pricing_dag, task_id=Create_dummy_variables, execution_date=20211205T000000, start_date=20211206T162539, end_date=20211206T162549
[2021-12-06 11:25:49,914] {standard_task_runner.py:88} ERROR - Failed to execute job 18 for task Create_dummy_variables
Traceback (most recent call last):
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: create_dummy_vars() missing 1 required positional argument: 'dataset'
[2021-12-06 11:25:49,955] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-06 11:25:49,984] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
